[project]
name = "vnmcpserver"
version = "0.1.0"
description = "Versa Networks MCP server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pyjwt>=2.10.1",
    "requests>=2.32.3",
]
